### ISSUE TITLE
Proteus is broken with Principia.

### ISSUE THREAD

**Issue by zilti** [PhineasFreak/RSSExpansion#2]
Here's the error I get upon starting a new game: (I removed Hyperion since it lacks Principia configs)

```
Error extending trajectory for Proteus. Error trying to fit a smooth polynomial to the trajectory. The approximation error jumped from +1.00000000000000002e-03 m to +1.05203802135734051e+08 m at time -1.54677600000000000e+09 s. The last position is {-9.46747295803405312e+13 m, -1.66058967229531000e+14 m, -4.77682467018191328e+13 m} and the last velocity is {-3.02608127619744232e+06 m s^-1, -5.27990642225241195e+06 m s^-1, -1.51334792961667338e+06 m s^-1}. An apocalypse occurred and two celestials probably collided because your solar system is unstable.
```

**Comment by zilti** [comment]
Actually, as I looked at the log file, much more seems to be broken: https://gist.github.com/zilti/d5388220a74de502442a67d1bf0aa117

**Comment by PhineasFreak** [comment]
Yea...to be honest **i** never really test the Principia configs. Other users used this pack in conjuction with Principia but they did not report back if it works or not so thank you for pointing these errors out and fixing them!
